// App Reducer
export const ADD_APPLICATION = "ADD_APPLICATION";
export const CHANGE_APPLICATION = "CHANGE_APPLICATION";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

// Application Reducer
export const ADD_CPU_UTILISATION = "ADD_CPU_UTILISATION";
export const ADD_MEMORY_UTILIZATION = "ADD_MEMORY_UTILIZATION";
export const ADD_EVENT_HISTORY = "ADD_EVENT_HISTORY";

